
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

$start.NOTIFICATIONS=swaync # dunst
exec-once = swayosd-server # enable swayosd service
exec-once = pypr
$QUICKAPPS = stremio pamac-manager # used for quick app launcher
$BROWSER = zen-browser # default browser, if commented out , will use the default browser
$EDITOR = zeditor # default editor, if commented out , will use the default editor
$EXPLORER= nautilus # default file manager, if commented out , will use the default file manager
$TERMINAL = kitty # default terminal, if commented out , will use the org.gnome.desktop.default-applications.terminal
$LOCKSCREEN=hyprlock # default lockscreen, you can use any lockscreen you want, eg swaylock
$IDLE=hypridle # default idle manager, you can use any idle manager you want,eg swayidle

general {
    gaps_in = 1
    gaps_out = 2
    border_size = 1
   }

decoration {
    rounding = 8
    dim_special = 0.3
    active_opacity = 1
    inactive_opacity = 0.85
    fullscreen_opacity = 1
    blur {
        special = true
    }
     shadow {
        enabled = false
        ignore_window = true
        offset = 0 0
        range = 15
        render_power = 1
        color = 0x80ffffff
    }
}
input {
    sensitivity = 1
    force_no_accel = 0

}
layerrule = unset,waybar
layerrule = blur , fabric
layerrule = ignorezero, fabric
layerrule = blur ,gtk-layer-shell
layerrule = ignorezero ,gtk-layer-shell

bind = $mainMod, H, exec, sudo /usr/local/bin/keyboard_switch.sh
bind = $mainMod, T, exec, $TERMINAL
bind = $mainMod, E, exec, $EXPLORER
# bind = $mainMod, C, exec, $EDITOR
bind = $mainMod, B, exec, $BROWSER
$rofi-launch=$scrPath/rofilaunch.sh
bind = $mainMod, A, exec, pkill -x rofi || $rofi-launch d
bind = $mainMod, C, exec,  pypr wall next

windowrulev2 = float,initialtitle:^(Select Setup Install Mode)$
windowrulev2 = float,title:^(Select Setup Install Mode)$
windowrulev2 = float,class:^(microsip.exe)$
windowrulev2 = float,class:^(explorer.exe)$
windowrulev2 = float,title:^(Wine configuration)$
